Disable mirror.dkm.cz repository
Reason: repository declares a file that does not exist
A problem occurred configuring project ':spoofax3.lwb.root'.
> Could not resolve all dependencies for configuration ':spoofax3.lwb.root:classpath'.
   > java.io.FileNotFoundException: https://mirror.dkm.cz/eclipse//technology/epp/downloads/release/2020-06/R/eclipse-committers-2020-06-R-macosx-cocoa-x86_64.dmg